### ISSUE TITLE
识别超星缓冲器路径有待改进

### ISSUE THREAD

**Issue by itspidercn** [PettterWang/pdz-assistant#6]
win10 LTSC，超星阅读器 v5.4.22518
系统%temp%不在C盘，而是内存虚盘R:\temp
超星阅读器的缓冲器路径是R:\temp\buffer，阅读pdz文件时产生的bmp文件确认都在此。
但pdz助手中识别不了这个路径，“查看缓冲器”按钮为禁止色。

创建了一个VMware下的win10 LTSC虚拟机，系统temp在默认的C盘下，pdz助手就能正常工作。
希望优化一下路径识别逻辑，谢谢。

**Comment by itspidercn** [comment]
![image](https://github.com/PettterWang/pdz-assistant/assets/62824108/0d1f0224-0df6-4682-81f6-6c923109aa10)

**Comment by whaleday** [comment]
可以通过修改Form1.cs第540行的路径再用vs重新生成解决这个问题https://github.com/PettterWang/pdz-assistant/blob/582fab6f0b786e16be988134571e73911bc2badb/Form1.cs#L540 但我直接生成后除了多出来一堆依赖外使用时的翻页速度也明显下降，可能是我的打包方式不对毕竟我也没有学过c#
一个更好的解决方法是使用dnspy直接修改发行的exe文件，将`this.缓冲器路径`改成你的buffer路径就可以了
<img width="785" alt="Snipaste_2024-03-30_03-40-12" src="https://github.com/PettterWang/pdz-assistant/assets/103437430/9c9aaff7-05d4-4587-b25a-84549beb4267">

**Comment by itspidercn** [comment]
多谢指导。在dbSpy中改成这样，查看缓冲区就就ok了
`	this.缓冲器路径 = Path.GetTempPath() + "\\buffer";`
 
但是“一键转换”还是禁止色，看原因貌似因为检测到“ssReader未处于阅读模式”，但实际ssReader状态是正常的。
不知道如何解决？

**Comment by whaleday** [comment]
可以再检查一下超星阅读器的版本，之前我的超星阅读器更新成最新版后也出现了这个问题

**Comment by itspidercn** [comment]
> 可以再检查一下超星阅读器的版本，之前我的超星阅读器更新成最新版后也出现了这个问题

版本没变，临时解决方案是先打开助手，再启动超星，处理完一本，关闭超星。新书要重新打开超星
